require('./config')
const path = require('path')
const cors = require('cors')
const logger = require('morgan')
const db = require('./models/db')
const express = require('express')
const cookieParser = require('cookie-parser')
const global = require('./helpers/global_helper')

const app = express()
let appRoot = path.resolve(__dirname)

app.use(cors())
app.use(cookieParser())
app.use(express.json())
app.use(express.urlencoded({extended: false}))
app.use(express.static(path.join(__dirname, 'public')))
if (config.isLogging) app.use(logger('dev'))

global(db, app, appRoot, express)
require('./util/swagger.util')
require('./middleware/pageable')
require('./middleware/router')